export default {
    name:'pin',
    title:'pin',
    type:'document',
    fields:[
        {
            name:'title',
            title:'title',
            type:'string'
        },
        {
            name:'about',
            title:'about',
            type:'string'
        },
        {
            name:'destination',
            title:'destination',
            type:'url'
        },
        {
            name:'category',
            title:'category',
            type:'string'
        },
        {
            name:'pinimage',
            title:'pinimage',
            type:'image',
            options:{
                hotspot:true
            }
        } ,
        {
            name:'userid',
            title:'userid',
            type:'string'
        }
        ,
        {
            name:'postedby',
            title:'postedby',
            type:'postedby'
        }
        ,
        {
            name:'save',
            title:'save',
            type:'array',
            of:[{type:'save'}]
        }
        ,
        {
            name:'comments',
            title:'comments',
            type:'array',
            of:[{type:'comment'}]
        }
    ]
}